--- 
- name: Task Failure Exercise 
  hosts: localhost
  vars:
    #web_package: http
    web_package: apache2
    db_package: mariadb-server 
    db_service: mariadb
  tasks:
    - name: Check local time 
      shell: "date +%Y-%m-%d%H-%M-%S"
      register: command_result 
      changed_when: false
    - name: Print local time 
      debug: 
        var: command_result.stdout 
    # - block:  
    #     - name: Install {{ web_package }} packages
    #       apt:
    #         name: "{{ web_package }}"
    #         state: present
    #   rescue:
    #     - name: Install {{ db_package }} db_packages
    #       apt:
    #         name: "{{ db_package }}"
    #         state: present 
    #   always:
    #     - name: Start {{ db_service }} service
    #       service:
    #         name: "{{ db_service }}"
    #         state: started 
