---
- name: Simple Boolean Task Demo
  hosts: localhost
  vars: 
    run_my_task: true

  tasks:
    - name: apache2 package is installed
      apt:
        name: apache2
        state: absent
      when: run_my_task